name: Setup Dependencies
description: Setup dependencies

inputs:
  setup_java:
    description: "Setup Java and Gradle"
    required: false
    default: false
    type: boolean
  native_active:
    description: "Setup native dependencies"
    required: false
    default: false
    type: boolean

runs:
  using: composite
  steps:
    - name: Install ccache
      if: ${{ inputs.setup_java == 'true' && inputs.native_active == 'true' }}
      shell: bash
      run: sudo apt-get install -y ccache

    - name: Install mise
      uses: jdx/mise-action@v4
      with:
        tool_versions: |
          ruby 3.4.8
          nodejs 24
          ${{ inputs.setup_java == 'true' && 'java zulu-17' || '' }}

    - name: Setup Gradle
      if: ${{ inputs.setup_java == 'true' && inputs.native_active == 'true' }}
      uses: gradle/actions/setup-gradle@v5
      with:
        add-job-summary: 'on-failure'

    - name: Cache ccache
      if: ${{ inputs.setup_java == 'true' && inputs.native_active == 'true' }}
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/.ccache
        key: ccache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ccache-${{ runner.os }}-

    - name: Get npm cache directory
      shell: bash
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Cache npm
      uses: actions/cache@v5
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Cache android/.gradle
      if: ${{ inputs.setup_java == 'true' && inputs.native_active == 'true' }}
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/android/.gradle
        key: ${{ runner.os }}-android-gradle-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-android-gradle-

    - name: Cache node modules
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install Node Modules
      shell: bash
      run: npm ci

    - name: Cache vendor/bundle
      if: ${{ inputs.native_active == 'true' }}
      uses: actions/cache@v5
      with:
        path: vendor
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Gems
      if: ${{ inputs.native_active == 'true' }}
      shell: bash
      run: bundle install

    - name: Install iOS Pods
      shell: bash
      if: ${{ inputs.setup_java != 'true' && inputs.native_active == 'true' }}
      run: npm run pod-install
