# frozen_string_literal: true

opt_out_usage

require_relative "utils/config_helper"
require_relative "utils/file_helper"
require_relative "utils/github_helper"

DEFAULT_EXPORT_METHOD   = "app-store"
XCODEBUILD_FORMATTER    = 'xcbeautify --renderer github-actions'

default_platform(:ios)
$setup_result = nil
$setup_android_result = nil

platform :ios do
  desc "Push a new build to TestFlight"

  before_all do |lane|
    pre_script = ConfigHelper.optional_env("BEFORE_ALL", default: nil)
    sh(pre_script) if pre_script
  end

  lane :setup do |options|
    next $setup_result unless $setup_result.nil?

    config = ConfigHelper.app_config(export_method: options[:export_method], platform: :ios)
    setup_ci if ENV['CI']
    clear_derived_data
    match_type = config[:match_type]
    puts "config: #{config}"
    FileHelper.decode_base64_to_file(
      config[:firebase_credentials_base64],
      config[:firebase_credentials_path]
    )

    # Read all native targets from the Xcode project
    target_identifier_map = Xcodeproj::Project.open(config[:project]).native_targets.map do |target|
      bundle_id = target.build_configurations.first.build_settings["PRODUCT_BUNDLE_IDENTIFIER"]
      { name: target.name, bundle_id: bundle_id }
    end

    api_key = app_store_connect_api_key(
      key_id: config[:key_id],
      issuer_id: config[:issuer_id],
      is_key_content_base64: true,
      key_content: config[:key_base64],
      in_house: config[:in_house]
    )

    match(
      type: match_type,
      app_identifier: target_identifier_map.map { |t| t[:bundle_id] },
      username: config[:match_username],
      clone_branch_directly: true,
      storage_mode: "git",
      git_url: config[:match_git_url],
      git_branch: config[:match_git_branch],
      api_key: api_key,
      readonly: is_ci,
      git_private_key: FileHelper.decode_base64(config[:match_git_private_key_base64])
    )

    cert_name = ENV["sigh_#{config[:app_identifier]}_#{match_type}_certificate-name"]
    targets = target_identifier_map.map do |target|
      bid = target[:bundle_id]
      {
        name: target[:name],
        bundle_id: bid,
        profile_uuid: ENV["sigh_#{bid}_#{match_type}"],
        profile_name: ENV["sigh_#{bid}_#{match_type}_profile-name"],
        profile_path: ENV["sigh_#{bid}_#{match_type}_profile-path"],
        cert_name: cert_name
      }
    end

    $setup_result = {
      config: config,
      api_key: api_key,
      targets: targets,
      cert_name: cert_name
    }
  end

  lane :internal do
    export_method = DEFAULT_EXPORT_METHOD
    result        = setup(export_method: export_method)
    config        = result[:config]
    api_key       = result[:api_key]

    latest_testflight_build_number(
      api_key: api_key,
      app_identifier: config[:app_identifier],
      initial_build_number: 0
    )

    build_number = lane_context[:LATEST_TESTFLIGHT_BUILD_NUMBER] + 1
    increment_build_number(
      xcodeproj: config[:project],
      skip_info_plist: false,
      build_number: build_number
    )

    archive_result = create_archive(export_method: export_method)

    ipa_result = create_ipa(
      export_method: export_method,
      archive_path: archive_result[:archive_path]
    )

    FileHelper.zip_folder(
      input_dir_path: config[:lane_output_directory],
      output_path: config[:zip_asset_path]
    )
    File.open(ENV['GITHUB_ENV'], 'a') { |f| f.puts("RELEASE_ASSET_PATH=#{config[:zip_asset_path]}") } if ENV['GITHUB_ENV']

    release_notes = GithubHelper.release_notes
    github_release = GithubHelper.create_release(
      version: ipa_result[:version],
      build_number: ipa_result[:build_number],
      release_notes: release_notes,
      upload_assets: [config[:zip_asset_path]]
    )

    testflight_params = {
      ipa: ipa_result[:path],
      api_key: api_key,
      app_identifier: config[:app_identifier],
      # If set to true, the distribute_external option won't work and no build will be distributed to testers. 
      # (You might want to use this option if you are using this action on CI and have to pay for 'minutes used' on your CI plan).
      # If set to true and a changelog is provided, it will partially wait for the build to appear on AppStore Connect
      # so the changelog can be set, and skip the remaining processing steps
      skip_waiting_for_build_processing: true,
      distribute_external: false
    }

    if config[:send_changelog_to_testflight]
      testflight_params[:changelog] = "#{release_notes}\nGithub Release(#{github_release[:id]}): #{github_release[:url]}"
    end

    upload_to_testflight(testflight_params)

    clean_build_artifacts
  end

  lane :adhoc do
    export_method = "ad-hoc"
    result  = setup(export_method: export_method)
    config  = result[:config]

    latest_release = firebase_app_distribution_get_latest_release(
      googleservice_info_plist_path: config[:googleservice_info_plist_path],
      service_credentials_file: config[:firebase_credentials_path]
    )

    build_number = (latest_release&.[](:buildVersion).to_i || 0) + 1
    increment_build_number(
      xcodeproj: config[:project],
      skip_info_plist: false,
      build_number: build_number
    )

    archive_result = create_archive(export_method: export_method)

    ipa_result = create_ipa(
      export_method: export_method,
      archive_path: archive_result[:archive_path]
    )

    FileHelper.zip_folder(
      input_dir_path: config[:lane_output_directory],
      output_path: config[:zip_asset_path]
    )
    File.open(ENV['GITHUB_ENV'], 'a') { |f| f.puts("RELEASE_ASSET_PATH=#{config[:zip_asset_path]}") } if ENV['GITHUB_ENV']

    release_notes = GithubHelper.release_notes
    github_release = GithubHelper.create_release(
      version: ipa_result[:version],
      build_number: ipa_result[:build_number],
      release_notes: release_notes,
      upload_assets: [config[:zip_asset_path]]
    )

    firebase_app_distribution(
      service_credentials_file: config[:firebase_credentials_path],
      groups: "internal",
      release_notes: "#{release_notes}\nGithub Release(#{github_release[:id]}): #{github_release[:url]}",
      ipa_path: ipa_result[:path]
    )

    clean_build_artifacts
  end

  lane :create_archive do |options|
    result         = setup(export_method: options[:export_method] || DEFAULT_EXPORT_METHOD)
    targets        = result[:targets]
    config         = result[:config]
    cert_name      = result[:cert_name]
    archive_path   = options[:archive_path] || config[:xcarchive_path]

    app_target   = targets.find { |t| t[:bundle_id] == config[:app_identifier] }
    version      = get_version_number(xcodeproj: config[:project], target: app_target[:name])
    build_number = get_build_number(xcodeproj: config[:project])

    targets.each do |target|
      update_code_signing_settings(
        use_automatic_signing: false,
        team_id: config[:team_id],
        path: config[:project],
        bundle_identifier: target[:bundle_id],
        profile_name: target[:profile_name],
        profile_uuid: target[:profile_uuid],
        targets: target[:name],
        code_sign_identity: target[:cert_name]
      )
    end

    # Archive
    build_app(
      workspace: config[:workspace],
      scheme: config[:scheme],
      silent: config[:silent],
      configuration: config[:configuration],
      xcodebuild_formatter: XCODEBUILD_FORMATTER,
      archive_path: archive_path,
      skip_profile_detection: true,
      codesigning_identity: cert_name,
      skip_build_archive: false,
      skip_codesigning: true,
      skip_package_ipa: true,
      export_method: config[:export_method],
      export_team_id: config[:team_id],
      export_options: {
        method: config[:export_method],
        compile_bitcode: true,
        provisioningProfiles: targets.each_with_object({}) { |t, h| h[t[:bundle_id]] = t[:profile_uuid] }
      }
    )

    {
      version: version,
      build_number: build_number,
      archive_path: lane_context[SharedValues::XCODEBUILD_ARCHIVE],
    }
  end

  lane :create_ipa do |options|
    result       = setup(export_method: options[:export_method] || DEFAULT_EXPORT_METHOD)
    targets      = result[:targets]
    config       = result[:config]
    cert_name    = result[:cert_name]
    archive_path = options[:archive_path] || config[:xcarchive_path]
    output_dir   = options[:output_directory] || config[:ipa_output_directory]

    archive_info = Plist.parse_xml("#{archive_path}/Info.plist")
    app_props    = archive_info["ApplicationProperties"]
    version      = app_props["CFBundleShortVersionString"]
    build_number = app_props["CFBundleVersion"]

    # Create IPA
    build_app(
      workspace: config[:workspace],
      scheme: config[:scheme],
      silent: config[:silent],
      configuration: config[:configuration],
      output_name: config[:scheme],
      xcodebuild_formatter: XCODEBUILD_FORMATTER,
      archive_path: archive_path,
      output_directory: output_dir,
      skip_profile_detection: true,
      codesigning_identity: cert_name,
      skip_build_archive: true,
      skip_codesigning: false,
      skip_package_ipa: false,
      export_method: config[:export_method],
      export_team_id: config[:team_id],
      export_options: {
        method: config[:export_method],
        compile_bitcode: true,
        provisioningProfiles: targets.each_with_object({}) { |t, h| h[t[:bundle_id]] = t[:profile_uuid] }
      }
    )

    {
      version: version,
      build_number: build_number,
      path: lane_context[SharedValues::IPA_OUTPUT_PATH]
    }
  end

  lane :resign_ipa do |options|
    result    = setup(export_method: options[:export_method] || DEFAULT_EXPORT_METHOD)
    targets   = result[:targets]
    cert_name = result[:cert_name]

    resign(
      ipa: options[:ipa_path],
      signing_identity: cert_name,
      provisioning_profile: targets.each_with_object({}) { |t, h| h[t[:bundle_id]] = t[:profile_path] }
    )
  end
end

platform :android do
  desc "Push a new build to Firebase App Distribution"

  before_all do |lane|
    pre_script = ConfigHelper.optional_env("BEFORE_ALL", default: nil)
    sh(pre_script) if pre_script
  end

  lane :setup do |options|
    next $setup_android_result unless $setup_android_result.nil?

    config = ConfigHelper.android_config(export_method: options[:export_method], platform: :android)

    FileHelper.decode_base64_to_file(
      config[:firebase_credentials_base64],
      config[:firebase_credentials_path]
    )
    FileHelper.decode_base64_to_file(
      config[:key_store_base64],
      config[:key_store_path]
    )
    FileHelper.decode_base64_to_file(
      config[:play_store_credentials_base64],
      config[:play_store_credentials_path]
    )

    $setup_android_result = {
      config: config
    }
  end

  lane :internal do |options|
    result        = setup(export_method: options[:export_method] || "aab")
    config        = result[:config]

    version_codes = google_play_track_version_codes(
      package_name: config[:app_identifier],
      track: "internal",
      json_key: config[:play_store_credentials_path]
    )

    latest_build_number = version_codes.empty? ? 0 : version_codes.first
    new_build_number = latest_build_number + 1

    increment_version_code(
      gradle_file_path: config[:app_gradle_file_path],
      version_code: new_build_number
    )

    gradle(
      task: config[:task],
      build_type: config[:build_type],
      print_command: false,
      project_dir: config[:project_dir],
      gradle_path: config[:gradle_path],
      properties: {
        "android.injected.signing.store.file" => config[:key_store_path],
        "android.injected.signing.store.password" => config[:key_store_password],
        "android.injected.signing.key.alias" => config[:key_alias],
        "android.injected.signing.key.password" => config[:key_password],
        # "android.injected.version.code" => 100,
        # "android.injected.version.name" => "1.0.0",
        "org.gradle.jvmargs" => "-Xmx4096m -XX:MaxMetaspaceSize=2048m",
      }
    )

    apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    aab_path = lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]

    FileHelper.zip_folder(
      input_dir_path: config[:export_method] == "apk" ? File.dirname(apk_path) : File.dirname(aab_path),
      output_path: config[:zip_asset_path]
    )
    File.open(ENV['GITHUB_ENV'], 'a') { |f| f.puts("RELEASE_ASSET_PATH=#{config[:zip_asset_path]}") } if ENV['GITHUB_ENV']

    release_notes = GithubHelper.release_notes
    version_name = android_get_version_name(gradle_file: config[:app_gradle_file_path])

    github_release = GithubHelper.create_release(
      platform: :android,
      version: version_name,
      build_number: new_build_number,
      release_notes: release_notes,
      upload_assets: [config[:zip_asset_path]]
    )

    play_store_params = {
      package_name: config[:app_identifier],
      track: "internal",
      release_status: "draft",
      json_key: config[:play_store_credentials_path]
    }

    if config[:export_method] == "apk"
      play_store_params[:apk] = apk_path
    else
      play_store_params[:aab] = aab_path
    end

    upload_to_play_store(play_store_params)
  end
end