name: Setup Fastlane
description: Setup fastlane

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: appibara-ltd/nf-workflows
        path: ./nf_workflows

    - name: Move Fastlane
      shell: bash
      run: |
        if [ -d "./nf_fastlane" ]; then rm -rf ./nf_fastlane; fi
        mv ./nf_workflows/fastlane ./nf_fastlane

    - name: Remove nf_workflows
      shell: bash
      run: rm -rf ./nf_workflows
