name: Setup Fastlane
description: Setup fastlane
inputs:
  sdk_version:
    description: "Nativeflow sdk version"
    default: "0.0.1"
  sdk_location:
    description: "Nativeflow sdk location to download"
    default: "nativeflow.app"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: appibara-ltd/nf-workflows
        path: ./nf_workflows

    - name: Move Fastlane
      shell: bash
      run: |
        if [ -d "./fastlane" ]; then rm -rf ./fastlane; fi
        mv ./nf_workflows/fastlane ./fastlane

    - name: Remove nf_workflows
      shell: bash
      run: rm -rf ./nf_workflows

    - name: Move Bundle Config
      shell: bash
      run: |
        if [ -d "./.bundle" ]; then rm -rf ./.bundle; fi
        mv ./fastlane/.bundle ./.bundle
        
    - name: Move Gemfile
      shell: bash
      run: |
        if [ -d "./Gemfile" ]; then rm -rf ./Gemfile; fi
        if [ -d "./Gemfile.lock" ]; then rm -rf ./Gemfile.lock; fi
        mv ./fastlane/Gemfile ./Gemfile
        mv ./fastlane/Gemfile.lock ./Gemfile.lock


