name: Test Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory for the project"
        required: false
        type: string
        default: "."

jobs:
  npm-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Step From Test Workflow
        run: echo "Step From Test Workflow"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v3

      - name: Get npm cache directory
        id: npm_cache_dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm_cache_dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node Modules
        run: npm ci

  bundle-install:
    needs: npm-install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v3

      - name: Cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: bundle install
